---
# roles/node-exporter/defaults/main.yml

# Node exporter version
node_exporter_version: "1.8.1"

# Port to listen on — WireGuard IP only, set per-host
node_exporter_listen: "0.0.0.0"
node_exporter_port: 9100

# Binary location
node_exporter_bin: "/usr/local/bin/node_exporter"

# User
node_exporter_user: "node-exporter"